# Generated by Django 5.2.1 on 2025-07-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comments_contact',
            field=models.TextField(default='', verbose_name='Comentarios'),
            preserve_default=False,
        ),
    ]
