# Generated by Django 5.2.1 on 2025-07-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_contact', models.AutoField(primary_key=True, serialize=False)),
                ('name_contact', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname_contact', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_contact', models.CharField(max_length=10, verbose_name='Telefono')),
                ('comments_contact', models.TextField(verbose_name='Comentarios')),
                ('date_contact', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('status_contact', models.BooleanField(default=False, verbose_name='Estado')),
                ('seen_contact', models.BooleanField(default=False, verbose_name='Visualizado')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contact',
                'ordering': ['id_contact'],
            },
        ),
    ]
