# Generated by Django 5.2.1 on 2025-07-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='seen_contact',
            field=models.CharField(choices=[('NO', 'No visto'), ('SI', 'Visto')], default='NO', max_length=2, verbose_name='Visualizado'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status_contact',
            field=models.CharField(choices=[('NO_ATENDIDO', 'No atendido'), ('EN_CURSO', 'En curso'), ('ATENDIDO', 'Atendido')], default='NO_ATENDIDO', max_length=15, verbose_name='Estado'),
        ),
    ]
