# Generated by Django 5.2.1 on 2025-07-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contact_seen_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='seen_contact',
            field=models.CharField(choices=[('No visto', 'No visto'), ('Visto', 'Visto')], default='No visto', max_length=100, verbose_name='Visualizado'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status_contact',
            field=models.CharField(choices=[('NO_ATENDIDO', 'No atendido'), ('EN_CURSO', 'En curso'), ('ATENDIDO', 'Atendido')], default='NO_ATENDIDO', max_length=100, verbose_name='Estado'),
        ),
    ]
