# Generated by Django 4.2.16 on 2026-05-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contact_seen_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id_contact'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
    ]
